apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-BEA
  description: An example deployment of a Backstage application for BEA.
  annotations:
    github.com/project-slug: mupe990216/backstage-demo
spec:
  type: website
  owner: backstage/maintainers
  lifecycle: experimental
